Repository aquality-automation/aquality-selenium-java, pull requests merged in 2024-02, with the labels that each got.

#123 [Feature] Find elements by image
  pom.xml
  src/main/java/aquality/selenium/browser/JavaScript.java
  src/main/java/aquality/selenium/elements/interfaces/ByImage.java
  src/main/resources/js/getDevicePixelRatio.js
  src/main/resources/js/getElementsFromPoint.js
  src/test/java/manytools/ManyToolsForm.java
  src/test/java/tests/integration/LocatorTests.java
  src/test/java/theinternet/forms/BrokenImagesForm.java
  src/test/resources/brokenImage.png
Labels: feature

#127 [Enhancement] Use native function to open new tab
  src/main/java/aquality/selenium/browser/Browser.java
  src/main/java/aquality/selenium/browser/BrowserNavigation.java
  src/main/java/aquality/selenium/browser/BrowserTabNavigation.java
  src/main/java/aquality/selenium/browser/IBrowserTabNavigation.java
  src/test/java/tests/integration/BrowserTabsTests.java
Labels: enhancement

#105 [Feature] Add multichoice combobox
  src/main/java/aquality/selenium/elements/ComboBox.java
  src/main/java/aquality/selenium/elements/ElementFactory.java
  src/main/java/aquality/selenium/elements/ElementType.java
  src/main/java/aquality/selenium/elements/MultiChoiceBox.java
  src/main/java/aquality/selenium/elements/interfaces/IElementFactory.java
  src/main/java/aquality/selenium/elements/interfaces/IMultiChoiceBox.java
  src/main/resources/localization/be.json
  src/main/resources/localization/en.json
  src/main/resources/localization/pl.json
  src/main/resources/localization/ru.json
  src/main/resources/localization/uk.json
  src/test/java/tests/integration/elements/ElementTests.java
  src/test/java/tests/integration/elements/HiddenElementsTests.java
  src/test/java/tests/integration/elements/MultiChoiceBoxTests.java
  src/test/java/w3schools/W3SchoolsPage.java
  src/test/java/w3schools/forms/SelectMultipleForm.java
  src/test/resources/TestSuite.xml
Labels: feature

#137 Highlight elements correctly
  src/main/java/aquality/selenium/elements/Element.java
  src/main/java/aquality/selenium/elements/actions/JsActions.java
  src/test/java/tests/usecases/BrowserConcurrencyTests.java
Labels: bug, enhancement

#138 [Breaking] Migrate to Java 11 +semver: feature
  .github/workflows/release-maven-central.yml
  README.md
  azure-pipelines.yml
  pom.xml
  src/test/java/tests/usecases/devtools/DeviceEmulationTest.java
  src/test/java/tests/usecases/devtools/NetworkSpeedEmulationTest.java
  src/test/java/tests/usecases/devtools/OverrideUserAgentTest.java
Labels: feature, dependencies, java
